### ISSUE TITLE
Running RCP image on K32W USB dongle

### ISSUE THREAD

**Issue by maunishpatel1** [openthread/ot-nxp#102]
I have purchased new K32W USB dongles. I am trying to run openthread sample example on an ubuntu machine with  K32W dongle.

I have created RCP image for k32w  dongle from openthread github.(https://github.com/openthread/ot-nxp/blob/main/src/k32w0/k32w061/README.md)

I am running ot-deamon on the ubuntu PC using following command

#ot-daemon -v 'spinel+hdlc+uart:///dev/ttyUSB1?uart-baudrate=115200'.

But ot-deamon is failing to communicate with the K32W dongle and giving following error

[./build/posix/src/posix/ot-daemon[23634]: Running OPENTHREAD/20200818-01178-gdeb2a4c97; POSIX; Aug 25 2021 15:50:40
./build/posix/src/posix/ot-daemon[23634]: Thread version: 3
./build/posix/src/posix/ot-daemon[23634]: [CRIT]-PLAT----: HandleRcpTimeout() at /home/maunish/src/openthread/src/posix/../../src/lib/spinel/radio_spinel_impl.hpp:2204: RadioSpinelNoResponse]

Do i need to make specific changes to communicate over USB for the dongle?

is there any ready example for open thread RCP Image present for k32w?

**Comment by doru91** [comment]
Hi, @maunishpatel1 . The error that you are getting is due to an OpenThread version mismatch: while the host was compiled with Thread 1.2 support, the RCP has only Thread 1.1 support. The solution is to also build the host with Thread 1.1 support only:

`doru@ubuntu:~/Desktop/public_repos/ot-nxp/openthread$ ./script/cmake-build posix -DOT_DAEMON=ON -DOT_THREAD_VERSION=1.1`

Thread 1.2 support for NXP K32W061 will come soon.

**Comment by dlq84** [comment]
I've been struggling with getting the NXP OM15080-K32W USB dongle to work as well. Been trying a lot of different things over the course of a few day, what finally worked was changing a few build few things in the build script (script/build_k32w061).

```
diff --git a/openthread b/openthread
index c2773c3..ce77ab3 160000
--- a/openthread
+++ b/openthread
@@ -1 +1 @@
-Subproject commit c2773c3d8de1b72f04720de0ddcbca00e715ec12
+Subproject commit ce77ab3c1d7ad91b284615112ae38c08527bf73e
diff --git a/script/build_k32w061 b/script/build_k32w061
index 6d12070..83e48a5 100755
--- a/script/build_k32w061
+++ b/script/build_k32w061
@@ -39,7 +39,8 @@ readonly OT_OPTIONS=(
     "-DOT_SLAAC=ON"
 )
 readonly OT_OPTIONS_RCP_ONLY_UART_FLOW_CONTROL=(
-    "-DOT_RCP_FLOW_CONTROL=ON"
+    # "-DOT_RCP_FLOW_CONTROL=ON"
+    "-DOT_APP_NCP=ON" # ADDED BY ME
     "-DOT_APP_CLI=OFF"
     "-DOT_FTD=OFF"
     "-DOT_MTD=OFF"
```

Notice how I also went with the latest openthread (main as of today `ce77ab3c1d7ad91b284615112ae38c08527bf73e`) and the ot-nxp commit I'm on is `c58f459227c19344ae2a417f6fe448d77af8283f`. It's probably fine to use the default openthread submodule commit though...

And then I made sure otbr was build with Thread 1.1, since that's what the nxp supports, just like doru91 says. I rebuilt ot-br-posix with this patch (don't forget to delete the build folder first):

```
diff --git a/third_party/openthread/CMakeLists.txt b/third_party/openthread/CMakeLists.txt
index 82c444f65..59a6d3f8a 100644
--- a/third_party/openthread/CMakeLists.txt
+++ b/third_party/openthread/CMakeLists.txt
@@ -26,6 +26,7 @@
 #  POSSIBILITY OF SUCH DAMAGE.
 #
 
+set(OT_THREAD_VERSION 1.1 CACHE STRING "Thread 1.1" FORCE)
 set(OT_BORDER_AGENT ON CACHE BOOL "enable border agent" FORCE)
 set(OT_BORDER_ROUTER ON CACHE BOOL "enable border router feature" FORCE)
 set(OT_BORDER_ROUTING ${OTBR_BORDER_ROUTING} CACHE BOOL "enable border routing feature" FORCE)
```

And that's it. Hope that helps.

**Comment by jwhui** [comment]
Closing stale issue.
