### ISSUE TITLE
Upgarde the Openthread Version of REED K32W End device

### ISSUE THREAD

**Issue by dipVyas92** [openthread/ot-nxp#488]
Hi,

We used a hybrid REED device example of **NXP SDK version 2.6.4** to develop one custom application. Now we want an upgrade the REED End device's Openthread version from **1.1 to 1.3**.

If we use **SDK v2.6.9**, then we fulfill this requirement? Or is there any other way to upgrade Opthread version?

How to check the Openthred version in SDK?

**Can anyone help me to understand this?**

**Comment by mihai-ignat** [comment]
Hello, @dipVyas92 .
The latest development of ot-nxp and the K32W0 SDK doesn't include the OpenThread hybrid examples anymore. These have been discarded because the main focus for hybrid examples is [Matter](https://github.com/project-chip/connectedhomeip).
I encourage opening a post [here](https://community.nxp.com/t5/Wireless-Connectivity/bd-p/wireless-connectivity) to discuss further support.
BR,
Mihai

**Comment by mihai-ignat** [comment]
Hi, @dipVyas92.
Please create an NXP.com account and lets take the discussion further on [NXP Community](https://community.nxp.com/t5/Wireless-Connectivity/bd-p/wireless-connectivity).
Thanks.
Mihai

**Comment by dipVyas92** [comment]
I already create a ticket on the same.

Please check the below link.

https://community.nxp.com/t5/K32-L-Series-Microcontrollers/Upgarde-the-Openthread-Version-K32W-End-device/m-p/1641218
